-- PostgreSQL schema for the income CSV files.
-- Run this script before loading CSV data.
--
-- Correct result:
--   The database should store each income value once for each series/date pair.
--   Dates, series names, and source file information are kept in separate
--   tables so repeated text is not copied into every data row.
--
-- Main design:
--   income.income_series      = one row per income metric
--   income.observation_date   = one row per date
--   income.source_file        = one row per CSV file
--   income.series_source_file = junction between series and source files
--   income.income_observation = junction/fact table between series and dates

CREATE SCHEMA IF NOT EXISTS income;
CREATE SCHEMA IF NOT EXISTS income_stage;

-- Valid frequency values are stored once and reused by income_series.
-- This prevents spelling differences like monthly/month/Monthly.
CREATE TABLE IF NOT EXISTS income.series_frequency (
  frequency_code VARCHAR(16) PRIMARY KEY,
  frequency_name VARCHAR(32) NOT NULL UNIQUE
);

-- One row describes one income series, such as PI or RPI.
-- The actual time-series values are not stored here.
CREATE TABLE IF NOT EXISTS income.income_series (
  series_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_code VARCHAR(32) NOT NULL UNIQUE,
  series_name TEXT NOT NULL,
  frequency_code VARCHAR(16) NOT NULL,
  units TEXT NOT NULL,
  source_name TEXT NOT NULL,
  notes TEXT,
  CONSTRAINT income_series_frequency_fk
    FOREIGN KEY (frequency_code)
    REFERENCES income.series_frequency (frequency_code)
);

-- One row describes one CSV source file.
-- This helps track where each loaded value came from.
CREATE TABLE IF NOT EXISTS income.source_file (
  source_file_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name TEXT NOT NULL UNIQUE,
  file_description TEXT
);

-- Junction table: connects a series to the file that supplied it.
-- This keeps the design expandable if a future file contains several series.
CREATE TABLE IF NOT EXISTS income.series_source_file (
  series_id INTEGER NOT NULL,
  source_file_id INTEGER NOT NULL,
  PRIMARY KEY (series_id, source_file_id),
  CONSTRAINT series_source_file_series_fk
    FOREIGN KEY (series_id)
    REFERENCES income.income_series (series_id),
  CONSTRAINT series_source_file_source_file_fk
    FOREIGN KEY (source_file_id)
    REFERENCES income.source_file (source_file_id)
);

-- One row per calendar date used by the data.
-- Year/month/quarter are stored here so queries do not recalculate them.
CREATE TABLE IF NOT EXISTS income.observation_date (
  date_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_date DATE NOT NULL UNIQUE,
  observation_year SMALLINT NOT NULL,
  observation_month SMALLINT NOT NULL,
  observation_quarter SMALLINT NOT NULL,
  CONSTRAINT observation_month_check
    CHECK (observation_month BETWEEN 1 AND 12),
  CONSTRAINT observation_quarter_check
    CHECK (observation_quarter BETWEEN 1 AND 4)
);

-- Main fact/junction table.
-- The primary key forces one value per income series per date.
-- This is the rule that prevents duplicate rows in the correct schema.
CREATE TABLE IF NOT EXISTS income.income_observation (
  series_id INTEGER NOT NULL,
  date_id INTEGER NOT NULL,
  source_file_id INTEGER NOT NULL,
  observation_value NUMERIC NOT NULL,
  PRIMARY KEY (series_id, date_id),
  CONSTRAINT income_observation_series_fk
    FOREIGN KEY (series_id)
    REFERENCES income.income_series (series_id),
  CONSTRAINT income_observation_date_fk
    FOREIGN KEY (date_id)
    REFERENCES income.observation_date (date_id),
  CONSTRAINT income_observation_source_file_fk
    FOREIGN KEY (source_file_id)
    REFERENCES income.source_file (source_file_id)
);

-- Indexes make common joins and date filtering faster.
CREATE INDEX IF NOT EXISTS income_observation_date_idx
  ON income.income_observation (date_id);

CREATE INDEX IF NOT EXISTS income_observation_source_file_idx
  ON income.income_observation (source_file_id);

-- Seed lookup rows used by income.income_series.
INSERT INTO income.series_frequency (frequency_code, frequency_name)
VALUES
  ('monthly', 'Monthly'),
  ('quarterly', 'Quarterly'),
  ('annual', 'Annual')
ON CONFLICT (frequency_code) DO NOTHING;

-- Seed source file records. ON CONFLICT lets this script be re-run safely.
INSERT INTO income.source_file (file_name, file_description)
VALUES
  ('DSPI.csv', 'Disposable personal income source CSV'),
  ('FODSP.csv', 'FODSP source CSV'),
  ('MEHOINUSA646N.csv', 'Median household income in the United States source CSV'),
  ('PI.csv', 'Personal income source CSV'),
  ('RPI.csv', 'Real personal income source CSV')
ON CONFLICT (file_name) DO UPDATE
SET
  file_description = EXCLUDED.file_description;

-- Seed series metadata. Values are loaded later by 03_normalize_staged_income_data.sql.
INSERT INTO income.income_series
  (series_code, series_name, frequency_code, units, source_name, notes)
VALUES
  ('DSPI', 'Disposable personal income', 'monthly', 'Source numeric value', 'FRED/BEA', 'Monthly values from the DSPI CSV.'),
  ('FODSP', 'FODSP', 'quarterly', 'Source numeric value', 'FRED/source CSV', 'Quarterly values from the FODSP CSV; verify source definition before final reporting.'),
  ('MEHOINUSA646N', 'Median household income in the United States', 'annual', 'Dollars', 'FRED/Census', 'Annual value reported on January 1.'),
  ('PI', 'Personal income', 'monthly', 'Source numeric value', 'FRED/BEA', 'Monthly values from the PI CSV.'),
  ('RPI', 'Real personal income', 'monthly', 'Source numeric value', 'FRED/BEA', 'Monthly values from the RPI CSV.')
ON CONFLICT (series_code) DO UPDATE
SET
  series_name = EXCLUDED.series_name,
  frequency_code = EXCLUDED.frequency_code,
  units = EXCLUDED.units,
  source_name = EXCLUDED.source_name,
  notes = EXCLUDED.notes;

-- Link each series to its matching CSV source file.
INSERT INTO income.series_source_file (series_id, source_file_id)
SELECT
  s.series_id,
  f.source_file_id
FROM income.income_series s
JOIN income.source_file f
  ON f.file_name = s.series_code || '.csv'
ON CONFLICT DO NOTHING;

-- Long view:
--   One row per series/date/value. This is the cleanest shape for R plots
--   where color/grouping is based on series_code.
CREATE OR REPLACE VIEW income.v_income_observations_long AS
SELECT
  d.observation_date,
  d.observation_year,
  d.observation_month,
  d.observation_quarter,
  s.series_code,
  s.series_name,
  s.frequency_code,
  s.units,
  io.observation_value,
  sf.file_name AS source_file
FROM income.income_observation io
JOIN income.income_series s
  ON s.series_id = io.series_id
JOIN income.observation_date d
  ON d.date_id = io.date_id
JOIN income.source_file sf
  ON sf.source_file_id = io.source_file_id;

-- Wide view:
--   One row per date with one column per series. Missing values are expected
--   because monthly, quarterly, and annual series do not share every date.
CREATE OR REPLACE VIEW income.v_income_observations_wide AS
SELECT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  MAX(CASE WHEN series_code = 'DSPI' THEN observation_value END) AS disposable_personal_income,
  MAX(CASE WHEN series_code = 'FODSP' THEN observation_value END) AS fodsp,
  MAX(CASE WHEN series_code = 'MEHOINUSA646N' THEN observation_value END) AS median_household_income,
  MAX(CASE WHEN series_code = 'PI' THEN observation_value END) AS personal_income,
  MAX(CASE WHEN series_code = 'RPI' THEN observation_value END) AS real_personal_income
FROM income.v_income_observations_long
GROUP BY
  observation_date,
  observation_year,
  observation_month,
  observation_quarter;

-- Annual summary:
--   One row per year/series with simple summary values for reporting.
CREATE OR REPLACE VIEW income.v_income_annual_summary AS
SELECT
  observation_year,
  series_code,
  series_name,
  AVG(observation_value) AS average_value,
  MIN(observation_value) AS minimum_value,
  MAX(observation_value) AS maximum_value,
  COUNT(*) AS observation_count
FROM income.v_income_observations_long
GROUP BY
  observation_year,
  series_code,
  series_name;
