-- Intentionally malformed schema variation 1: duplicate rows.
--
-- Purpose:
--   This version keeps a mostly reasonable table structure, but removes the
--   natural uniqueness rule from observations. The same series/date value can
--   appear multiple times, which can inflate counts, averages, and display
--   density in R.
--
-- What the correct result should look like:
--   There should be only one value for each income series on each date.
--   The clean schema enforces this with PRIMARY KEY (series_id, date_id).
--
-- Where this version breaks:
--   income_bad_duplicates.income_observation uses a new observation_id as the
--   primary key and does not make (series_id, date_id) unique. That allows
--   repeated facts to be inserted.
--
-- Prerequisite:
--   Run 01_create_income_schema.sql, 02_create_and_populate_staging_tables.sql,
--   and 03_normalize_staged_income_data.sql first.

DROP SCHEMA IF EXISTS income_bad_duplicates CASCADE;
CREATE SCHEMA income_bad_duplicates;

CREATE TABLE income_bad_duplicates.income_series (
  series_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_code VARCHAR(32) NOT NULL,
  series_name TEXT NOT NULL,
  frequency_code VARCHAR(16) NOT NULL,
  units TEXT NOT NULL
);

CREATE TABLE income_bad_duplicates.source_file (
  source_file_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name TEXT NOT NULL
);

CREATE TABLE income_bad_duplicates.observation_date (
  date_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_date DATE NOT NULL,
  observation_year SMALLINT NOT NULL,
  observation_month SMALLINT NOT NULL,
  observation_quarter SMALLINT NOT NULL
);

-- Malformation:
--   There is no UNIQUE constraint on (series_id, date_id). The same fact can
--   be inserted repeatedly.
-- Display impact:
--   R can show extra points or inflated totals because the same date appears
--   more than once for the same series.
CREATE TABLE income_bad_duplicates.income_observation (
  observation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id INTEGER NOT NULL,
  date_id INTEGER NOT NULL,
  source_file_id INTEGER NOT NULL,
  observation_value NUMERIC NOT NULL,
  duplicate_batch VARCHAR(32) NOT NULL DEFAULT 'original',
  CONSTRAINT bad_duplicate_observation_series_fk
    FOREIGN KEY (series_id)
    REFERENCES income_bad_duplicates.income_series (series_id),
  CONSTRAINT bad_duplicate_observation_date_fk
    FOREIGN KEY (date_id)
    REFERENCES income_bad_duplicates.observation_date (date_id),
  CONSTRAINT bad_duplicate_observation_source_file_fk
    FOREIGN KEY (source_file_id)
    REFERENCES income_bad_duplicates.source_file (source_file_id)
);

-- Copy the clean data first, so this version starts with valid rows.
INSERT INTO income_bad_duplicates.income_series (
  series_code,
  series_name,
  frequency_code,
  units
)
SELECT DISTINCT
  series_code,
  series_name,
  frequency_code,
  units
FROM income.v_income_observations_long
ORDER BY series_code;

INSERT INTO income_bad_duplicates.source_file (file_name)
SELECT DISTINCT
  source_file
FROM income.v_income_observations_long
ORDER BY source_file;

INSERT INTO income_bad_duplicates.observation_date (
  observation_date,
  observation_year,
  observation_month,
  observation_quarter
)
SELECT DISTINCT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter
FROM income.v_income_observations_long
ORDER BY observation_date;

INSERT INTO income_bad_duplicates.income_observation (
  series_id,
  date_id,
  source_file_id,
  observation_value,
  duplicate_batch
)
SELECT
  s.series_id,
  d.date_id,
  sf.source_file_id,
  clean.observation_value,
  'original' AS duplicate_batch
FROM income.v_income_observations_long clean
JOIN income_bad_duplicates.income_series s
  ON s.series_code = clean.series_code
JOIN income_bad_duplicates.observation_date d
  ON d.observation_date = clean.observation_date
JOIN income_bad_duplicates.source_file sf
  ON sf.file_name = clean.source_file;

-- Duplicate the annual median household income rows exactly.
-- These duplicated years can make summaries and visual weighting misleading.
-- Specific break:
--   The same MEHOINUSA646N date/value is inserted twice.
INSERT INTO income_bad_duplicates.income_observation (
  series_id,
  date_id,
  source_file_id,
  observation_value,
  duplicate_batch
)
SELECT
  io.series_id,
  io.date_id,
  io.source_file_id,
  io.observation_value,
  'duplicate_median_income' AS duplicate_batch
FROM income_bad_duplicates.income_observation io
JOIN income_bad_duplicates.income_series s
  ON s.series_id = io.series_id
WHERE s.series_code = 'MEHOINUSA646N';

-- Duplicate every January monthly observation for the other income series.
-- Specific break:
--   January rows for DSPI, PI, and RPI are counted twice in summaries.
INSERT INTO income_bad_duplicates.income_observation (
  series_id,
  date_id,
  source_file_id,
  observation_value,
  duplicate_batch
)
SELECT
  io.series_id,
  io.date_id,
  io.source_file_id,
  io.observation_value,
  'duplicate_january_monthly' AS duplicate_batch
FROM income_bad_duplicates.income_observation io
JOIN income_bad_duplicates.income_series s
  ON s.series_id = io.series_id
JOIN income_bad_duplicates.observation_date d
  ON d.date_id = io.date_id
WHERE s.series_code IN ('DSPI', 'PI', 'RPI')
  AND d.observation_month = 1
  AND io.duplicate_batch = 'original';

-- Long display view:
--   This still displays, but duplicated rows remain visible.
CREATE OR REPLACE VIEW income_bad_duplicates.v_observations_long AS
SELECT
  d.observation_date,
  d.observation_year,
  d.observation_month,
  d.observation_quarter,
  s.series_code,
  s.series_name,
  s.frequency_code,
  s.units,
  io.observation_value,
  sf.file_name AS source_file,
  io.duplicate_batch
FROM income_bad_duplicates.income_observation io
JOIN income_bad_duplicates.income_series s
  ON s.series_id = io.series_id
JOIN income_bad_duplicates.observation_date d
  ON d.date_id = io.date_id
JOIN income_bad_duplicates.source_file sf
  ON sf.source_file_id = io.source_file_id;

-- Plot view:
--   This intentionally sums duplicated median-income rows. The clean result
--   should show the original annual value; this bad result shows inflated
--   values where duplicates exist.
CREATE OR REPLACE VIEW income_bad_duplicates.v_plot_data AS
SELECT
  observation_date AS date,
  SUM(observation_value) AS zhvi
FROM income_bad_duplicates.v_observations_long
WHERE series_code = 'MEHOINUSA646N'
GROUP BY observation_date
ORDER BY observation_date;

-- Summary view:
--   The observation_count column reveals duplicated rows. In the clean result,
--   annual median income should have one observation per year.
CREATE OR REPLACE VIEW income_bad_duplicates.v_annual_summary AS
SELECT
  observation_year,
  series_code,
  AVG(observation_value) AS average_value,
  COUNT(*) AS observation_count
FROM income_bad_duplicates.v_observations_long
GROUP BY
  observation_year,
  series_code
ORDER BY
  observation_year,
  series_code;
