-- Intentionally malformed schema variation 2: improperly normalized.
--
-- Purpose:
--   This version uses tables, but repeats descriptive series metadata on every
--   observation. The data can still display, but inconsistent labels, units,
--   and frequency text can split groups or make legends/summaries misleading.
--
-- What the correct result should look like:
--   Series names, units, and frequencies should be stored once in a series
--   table, then referenced by each observation.
--
-- Where this version breaks:
--   income_observation_flat repeats series_name, frequency_code, units, and
--   source_file in every row. Repeated text can drift out of sync.
--
-- Prerequisite:
--   Run 01_create_income_schema.sql, 02_create_staging_tables.sql, import the
--   CSVs, then run 03_normalize_staged_income_data.sql first.

DROP SCHEMA IF EXISTS income_bad_normalization CASCADE;
CREATE SCHEMA income_bad_normalization;

-- Malformation:
--   Series metadata belongs in a separate dimension table, but it is repeated
--   in the observation table instead.
-- Display impact:
--   If R groups by series_name or units, one real series can appear as several
--   different lines or legend entries.
CREATE TABLE income_bad_normalization.income_observation_flat (
  observation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_date DATE NOT NULL,
  observation_year SMALLINT NOT NULL,
  observation_month SMALLINT NOT NULL,
  observation_quarter SMALLINT NOT NULL,
  series_code VARCHAR(32) NOT NULL,
  series_name TEXT NOT NULL,
  frequency_code VARCHAR(16) NOT NULL,
  units TEXT NOT NULL,
  source_file TEXT NOT NULL,
  observation_value NUMERIC NOT NULL
);

-- Malformation:
--   This table stores file metadata redundantly by series_code instead of using
--   a stable source_file key.
-- Display impact:
--   The source information is still visible, but it is harder to trust because
--   there is no single source-file row controlling the label.
CREATE TABLE income_bad_normalization.series_file_note (
  note_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_code VARCHAR(32) NOT NULL,
  source_file TEXT NOT NULL,
  file_note TEXT NOT NULL
);

INSERT INTO income_bad_normalization.income_observation_flat (
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  source_file,
  observation_value
)
SELECT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  source_file,
  observation_value
FROM income.v_income_observations_long;

-- Intentionally introduce inconsistent descriptive fields.
-- Specific break:
--   Same series code, different display name for selected years.
UPDATE income_bad_normalization.income_observation_flat
SET series_name = 'Median Household Income'
WHERE series_code = 'MEHOINUSA646N'
  AND observation_year BETWEEN 2008 AND 2012;

-- Specific break:
--   Same series code, different units for later years.
UPDATE income_bad_normalization.income_observation_flat
SET units = 'USD'
WHERE series_code = 'MEHOINUSA646N'
  AND observation_year >= 2018;

-- Specific break:
--   Same series code, different frequency label for selected years.
UPDATE income_bad_normalization.income_observation_flat
SET frequency_code = 'yearly'
WHERE series_code = 'MEHOINUSA646N'
  AND observation_year IN (2001, 2005, 2010, 2015, 2020);

-- Specific break:
--   Same RPI series, different display label after 2020.
UPDATE income_bad_normalization.income_observation_flat
SET series_name = 'Real Personal Income, adjusted'
WHERE series_code = 'RPI'
  AND observation_year >= 2020;

INSERT INTO income_bad_normalization.series_file_note (
  series_code,
  source_file,
  file_note
)
SELECT DISTINCT
  series_code,
  source_file,
  'Repeated source metadata stored outside a proper source_file dimension.'
FROM income_bad_normalization.income_observation_flat;

-- Long display view:
--   The numeric values are still usable, but repeated labels may be inconsistent.
CREATE OR REPLACE VIEW income_bad_normalization.v_observations_long AS
SELECT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  observation_value,
  source_file
FROM income_bad_normalization.income_observation_flat;

-- Plot view:
--   The simple date/value plot still works. The malformed effect appears when
--   reports group or label data using the repeated text columns.
CREATE OR REPLACE VIEW income_bad_normalization.v_plot_data AS
SELECT
  observation_date AS date,
  observation_value AS zhvi
FROM income_bad_normalization.v_observations_long
WHERE series_code = 'MEHOINUSA646N'
ORDER BY observation_date;

-- This view shows how the malformed repeated labels can split what should be
-- one series into multiple apparent groups.
-- Correct result:
--   Each series_code should normally have one label/unit/frequency combination.
CREATE OR REPLACE VIEW income_bad_normalization.v_label_split_summary AS
SELECT
  series_code,
  series_name,
  frequency_code,
  units,
  COUNT(*) AS observation_count,
  MIN(observation_date) AS first_observation_date,
  MAX(observation_date) AS last_observation_date
FROM income_bad_normalization.v_observations_long
GROUP BY
  series_code,
  series_name,
  frequency_code,
  units
ORDER BY
  series_code,
  first_observation_date;
