-- Intentionally malformed schema variation 3: heavily malformed.
-- Run this script while connected to final_project_housing_analysis.
--
-- Purpose:
--   This version is denormalized, mixes datatypes, repeats facts, stores
--   numeric values as text in several columns, and includes conflicting value
--   copies. It can still display through v_plot_data, but charts and summaries
--   can be meaningfully distorted.
--
-- What the correct result should look like:
--   Dates should be DATE values, measurements should be NUMERIC values, and
--   each fact should exist once. Labels and source details should not be copied
--   into every measurement row.
--
-- Where this version breaks:
--   income_display_dump stores display text, source text, numeric values, text
--   values, duplicate facts, and quality notes all in one table.
--
-- Prerequisite:
--   Run 01_create_income_schema.sql, 02_create_and_populate_staging_tables.sql,
--   and 03_normalize_staged_income_data.sql first.

DROP SCHEMA IF EXISTS income_bad_heavy CASCADE;
CREATE SCHEMA income_bad_heavy;

-- Malformations:
--   * One table stores unrelated facts, labels, and source metadata.
--   * Dates are stored both as DATE and TEXT.
--   * Values are stored as NUMERIC and TEXT.
--   * Repeated fact columns store the same concept under different names.
--   * Some text values contain commas, currency symbols, blanks, and N/A.
--   * A row_quality column marks known problems instead of preventing them.
-- Display impact:
--   R may plot the wrong copy of a value, fail to convert text values cleanly,
--   or show duplicate/conflicting points for the same date.
CREATE TABLE income_bad_heavy.income_display_dump (
  dump_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_date DATE,
  observation_date_text TEXT,
  year_text TEXT,
  month_text TEXT,
  quarter_text TEXT,
  series_code TEXT,
  series_label TEXT,
  metric_name TEXT,
  frequency_or_units TEXT,
  source_file TEXT,
  source_note TEXT,
  observation_value NUMERIC,
  observation_value_text TEXT,
  duplicate_value_text TEXT,
  displayed_value TEXT,
  repeated_fact_1 NUMERIC,
  repeated_fact_2 NUMERIC,
  row_quality TEXT
);

-- Start with all clean rows, then deliberately damage copies of them below.
INSERT INTO income_bad_heavy.income_display_dump (
  observation_date,
  observation_date_text,
  year_text,
  month_text,
  quarter_text,
  series_code,
  series_label,
  metric_name,
  frequency_or_units,
  source_file,
  source_note,
  observation_value,
  observation_value_text,
  duplicate_value_text,
  displayed_value,
  repeated_fact_1,
  repeated_fact_2,
  row_quality
)
SELECT
  observation_date,
  TO_CHAR(observation_date, 'YYYY-MM-DD') AS observation_date_text,
  observation_year::TEXT AS year_text,
  observation_month::TEXT AS month_text,
  observation_quarter::TEXT AS quarter_text,
  series_code,
  series_name AS series_label,
  series_name AS metric_name,
  frequency_code || ' / ' || units AS frequency_or_units,
  source_file,
  'Repeated source and metric metadata in every row.' AS source_note,
  observation_value,
  observation_value::TEXT AS observation_value_text,
  observation_value::TEXT AS duplicate_value_text,
  observation_value::TEXT AS displayed_value,
  observation_value AS repeated_fact_1,
  observation_value AS repeated_fact_2,
  'original' AS row_quality
FROM income.v_income_observations_long;

-- Repeat the median income rows with slightly inflated numeric copies.
-- Specific break:
--   The same date now has both an original and a conflicting duplicate value.
--   A plot can show two points for one year or use the wrong one.
INSERT INTO income_bad_heavy.income_display_dump (
  observation_date,
  observation_date_text,
  year_text,
  month_text,
  quarter_text,
  series_code,
  series_label,
  metric_name,
  frequency_or_units,
  source_file,
  source_note,
  observation_value,
  observation_value_text,
  duplicate_value_text,
  displayed_value,
  repeated_fact_1,
  repeated_fact_2,
  row_quality
)
SELECT
  observation_date,
  observation_date_text,
  year_text,
  month_text,
  quarter_text,
  series_code,
  series_label || ' DUPLICATE',
  metric_name,
  frequency_or_units,
  source_file,
  source_note,
  observation_value * 1.03 AS observation_value,
  (observation_value * 1.03)::TEXT AS observation_value_text,
  observation_value_text,
  (observation_value * 1.03)::TEXT AS displayed_value,
  repeated_fact_1,
  repeated_fact_2 * 0.97 AS repeated_fact_2,
  'duplicate_conflicting_value' AS row_quality
FROM income_bad_heavy.income_display_dump
WHERE series_code = 'MEHOINUSA646N'
  AND row_quality = 'original';

-- Make selected text values hard to cast consistently.
-- Specific break:
--   Numeric values are copied into text with dollar signs and commas.
--   They may look nice, but they are no longer clean numbers.
UPDATE income_bad_heavy.income_display_dump
SET
  observation_value_text = '$' || TO_CHAR(observation_value, 'FM999,999,999.00'),
  displayed_value = '$' || TO_CHAR(observation_value, 'FM999,999,999.00'),
  row_quality = row_quality || ';currency_text'
WHERE series_code = 'MEHOINUSA646N'
  AND observation_date >= DATE '2015-01-01';

-- Specific break:
--   One repeated value field uses N/A text instead of a number.
UPDATE income_bad_heavy.income_display_dump
SET
  duplicate_value_text = 'N/A',
  row_quality = row_quality || ';na_text_copy'
WHERE series_code = 'FODSP'
  AND observation_date >= DATE '2010-01-01';

-- Specific break:
--   Dates are stored in two different text formats.
UPDATE income_bad_heavy.income_display_dump
SET
  observation_date_text = TO_CHAR(observation_date, 'MM/DD/YYYY'),
  row_quality = row_quality || ';alternate_date_format'
WHERE observation_date >= DATE '2020-01-01';

-- Conflicting repeated facts: display code may accidentally choose either one.
-- Specific break:
--   repeated_fact_1 and repeated_fact_2 disagree with the main value.
UPDATE income_bad_heavy.income_display_dump
SET
  repeated_fact_1 = observation_value * 0.90,
  repeated_fact_2 = observation_value * 1.10,
  row_quality = row_quality || ';conflicting_repeated_facts'
WHERE series_code IN ('PI', 'RPI')
  AND observation_date >= DATE '2020-01-01';

-- Long display view:
--   Keeps all malformed columns visible so the problems can be inspected.
CREATE OR REPLACE VIEW income_bad_heavy.v_observations_long AS
SELECT
  observation_date,
  observation_date_text,
  year_text,
  month_text,
  quarter_text,
  series_code,
  series_label,
  metric_name,
  frequency_or_units,
  source_file,
  observation_value,
  observation_value_text,
  duplicate_value_text,
  displayed_value,
  repeated_fact_1,
  repeated_fact_2,
  row_quality
FROM income_bad_heavy.income_display_dump;

-- Still displayable by the current R plotting script, but intentionally wrong:
-- it uses repeated_fact_2 when present, so the duplicate/conflicting copies can
-- bend the chart away from the clean median income series.
-- Correct result:
--   The plot should use the single numeric observation_value from the clean
--   schema, not a repeated copy from a denormalized dump table.
CREATE OR REPLACE VIEW income_bad_heavy.v_plot_data AS
SELECT
  observation_date AS date,
  COALESCE(repeated_fact_2, observation_value) AS zhvi
FROM income_bad_heavy.v_observations_long
WHERE series_code = 'MEHOINUSA646N'
ORDER BY
  observation_date,
  row_quality;

-- Summary view:
--   Shows how many rows fall into each problem group and what value would be
--   displayed if the wrong repeated value column is used.
CREATE OR REPLACE VIEW income_bad_heavy.v_malformed_display_summary AS
SELECT
  series_code,
  row_quality,
  COUNT(*) AS row_count,
  MIN(observation_date) AS first_observation_date,
  MAX(observation_date) AS last_observation_date,
  AVG(COALESCE(repeated_fact_2, observation_value)) AS displayed_average
FROM income_bad_heavy.v_observations_long
GROUP BY
  series_code,
  row_quality
ORDER BY
  series_code,
  row_quality;
