-- Intentionally malformed schema variation 4: incomplete data.
-- Run this script while connected to final_project_housing_analysis.
--
-- Purpose:
--   This version starts with the clean loaded data, then removes selected
--   observations. The original income schema is not changed.
--
-- What the correct result should look like:
--   Each series should keep all available observations for the 2000-2024
--   project range.
--
-- Where this version breaks:
--   income_bad_incomplete.income_observation_incomplete is missing arbitrary
--   years, months, and quarters. R can still plot it, but the chart will have
--   missing points and misleading gaps.
--
-- Prerequisite:
--   Run 01_create_income_schema.sql, 02_create_staging_tables.sql, import the
--   CSVs, then run 03_normalize_staged_income_data.sql first.

DROP SCHEMA IF EXISTS income_bad_incomplete CASCADE;
CREATE SCHEMA income_bad_incomplete;

CREATE TABLE income_bad_incomplete.income_observation_incomplete (
  observation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_date DATE NOT NULL,
  observation_year SMALLINT NOT NULL,
  observation_month SMALLINT NOT NULL,
  observation_quarter SMALLINT NOT NULL,
  series_code VARCHAR(32) NOT NULL,
  series_name TEXT NOT NULL,
  frequency_code VARCHAR(16) NOT NULL,
  units TEXT NOT NULL,
  source_file TEXT NOT NULL,
  observation_value NUMERIC NOT NULL
);

-- Keeps a record of what this bad schema removed.
-- This makes the break visible without modifying the clean data.
CREATE TABLE income_bad_incomplete.removed_observation_log (
  removed_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_date DATE NOT NULL,
  series_code VARCHAR(32) NOT NULL,
  observation_value NUMERIC NOT NULL,
  removal_reason TEXT NOT NULL
);

-- Copy the clean data first.
INSERT INTO income_bad_incomplete.income_observation_incomplete (
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  source_file,
  observation_value
)
SELECT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  source_file,
  observation_value
FROM income.v_income_observations_long;

-- Specific break:
--   Remove median household income for 2008-2012.
-- Display impact:
--   The annual median-income line jumps from 2007 to 2013.
INSERT INTO income_bad_incomplete.removed_observation_log (
  observation_date,
  series_code,
  observation_value,
  removal_reason
)
SELECT
  observation_date,
  series_code,
  observation_value,
  'Removed median household income years 2008-2012.'
FROM income_bad_incomplete.income_observation_incomplete
WHERE series_code = 'MEHOINUSA646N'
  AND observation_year BETWEEN 2008 AND 2012;

DELETE FROM income_bad_incomplete.income_observation_incomplete
WHERE series_code = 'MEHOINUSA646N'
  AND observation_year BETWEEN 2008 AND 2012;

-- Specific break:
--   Remove March and September rows from monthly personal income series.
-- Display impact:
--   Monthly lines have repeated missing months every year.
INSERT INTO income_bad_incomplete.removed_observation_log (
  observation_date,
  series_code,
  observation_value,
  removal_reason
)
SELECT
  observation_date,
  series_code,
  observation_value,
  'Removed March and September monthly observations.'
FROM income_bad_incomplete.income_observation_incomplete
WHERE series_code IN ('DSPI', 'PI', 'RPI')
  AND observation_month IN (3, 9);

DELETE FROM income_bad_incomplete.income_observation_incomplete
WHERE series_code IN ('DSPI', 'PI', 'RPI')
  AND observation_month IN (3, 9);

-- Specific break:
--   Remove later FODSP quarterly rows.
-- Display impact:
--   The quarterly FODSP series ends early compared with the clean data.
INSERT INTO income_bad_incomplete.removed_observation_log (
  observation_date,
  series_code,
  observation_value,
  removal_reason
)
SELECT
  observation_date,
  series_code,
  observation_value,
  'Removed FODSP observations after 2018.'
FROM income_bad_incomplete.income_observation_incomplete
WHERE series_code = 'FODSP'
  AND observation_year > 2018;

DELETE FROM income_bad_incomplete.income_observation_incomplete
WHERE series_code = 'FODSP'
  AND observation_year > 2018;

CREATE OR REPLACE VIEW income_bad_incomplete.v_observations_long AS
SELECT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  observation_value,
  source_file
FROM income_bad_incomplete.income_observation_incomplete;

-- Plot view:
--   Still returns date and zhvi for the current R plotting script, but the
--   missing median-income years make the display incomplete.
CREATE OR REPLACE VIEW income_bad_incomplete.v_plot_data AS
SELECT
  observation_date AS date,
  observation_value AS zhvi
FROM income_bad_incomplete.v_observations_long
WHERE series_code = 'MEHOINUSA646N'
ORDER BY observation_date;

-- Summary view:
--   Compares clean row counts with incomplete row counts.
CREATE OR REPLACE VIEW income_bad_incomplete.v_missing_data_summary AS
SELECT
  clean.series_code,
  clean.clean_row_count,
  COALESCE(bad.bad_row_count, 0) AS incomplete_row_count,
  clean.clean_row_count - COALESCE(bad.bad_row_count, 0) AS missing_row_count
FROM (
  SELECT
    series_code,
    COUNT(*) AS clean_row_count
  FROM income.v_income_observations_long
  GROUP BY series_code
) clean
LEFT JOIN (
  SELECT
    series_code,
    COUNT(*) AS bad_row_count
  FROM income_bad_incomplete.v_observations_long
  GROUP BY series_code
) bad
  ON bad.series_code = clean.series_code
ORDER BY clean.series_code;
