-- Intentionally malformed schema variation 5: mutated values.
-- Run this script while connected to final_project_housing_analysis.
--
-- Purpose:
--   This version starts with the clean loaded data, then changes selected
--   numeric values in the copied schema only. The original income schema is
--   not changed.
--
-- What the correct result should look like:
--   observation_value should match the source CSV value exactly after loading.
--
-- Where this version breaks:
--   income_bad_mutated.income_observation_mutated stores both original_value
--   and observation_value. observation_value is intentionally wrong for
--   selected rows.
--
-- Prerequisite:
--   Run 01_create_income_schema.sql, 02_create_staging_tables.sql, import the
--   CSVs, then run 03_normalize_staged_income_data.sql first.

DROP SCHEMA IF EXISTS income_bad_mutated CASCADE;
CREATE SCHEMA income_bad_mutated;

CREATE TABLE income_bad_mutated.income_observation_mutated (
  observation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_date DATE NOT NULL,
  observation_year SMALLINT NOT NULL,
  observation_month SMALLINT NOT NULL,
  observation_quarter SMALLINT NOT NULL,
  series_code VARCHAR(32) NOT NULL,
  series_name TEXT NOT NULL,
  frequency_code VARCHAR(16) NOT NULL,
  units TEXT NOT NULL,
  source_file TEXT NOT NULL,
  original_value NUMERIC NOT NULL,
  observation_value NUMERIC NOT NULL,
  mutation_type TEXT NOT NULL DEFAULT 'none',
  mutation_note TEXT
);

-- Copy the clean data first. original_value remains unchanged for comparison.
INSERT INTO income_bad_mutated.income_observation_mutated (
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  source_file,
  original_value,
  observation_value
)
SELECT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  source_file,
  observation_value AS original_value,
  observation_value
FROM income.v_income_observations_long;

-- Specific break:
--   Apply row-specific percentage increases between 5 and 15 percent.
--   random() is evaluated per selected row, so each changed row receives a
--   different multiplier each time this script is rerun.
-- Display impact:
--   PI and selected median-income values drift upward unevenly instead of
--   moving by one repeated fixed percentage.
WITH selected_mutations AS (
  SELECT
    observation_id,
    (1 + (0.05 + random() * 0.10))::numeric AS multiplier
  FROM income_bad_mutated.income_observation_mutated
  WHERE (
      series_code = 'PI'
      AND observation_month IN (2, 5, 8, 11)
      AND observation_year >= 2018
    )
    OR (
      series_code = 'MEHOINUSA646N'
      AND observation_year IN (2004, 2009, 2014, 2019, 2023)
    )
)
UPDATE income_bad_mutated.income_observation_mutated target
SET
  observation_value = target.original_value * selected_mutations.multiplier,
  mutation_type = 'row_specific_percentage_increase',
  mutation_note = 'Row-specific increase of '
    || ROUND(((selected_mutations.multiplier - 1) * 100)::numeric, 2)::text
    || ' percent.'
FROM selected_mutations
WHERE target.observation_id = selected_mutations.observation_id;

-- Specific break:
--   Apply row-specific percentage decreases between 5 and 15 percent.
--   Each selected row receives its own randomized drop.
-- Display impact:
--   RPI, DSPI, and FODSP develop uneven local dips that can distort trend and
--   forecast models without using one repeated multiplier.
WITH selected_mutations AS (
  SELECT
    observation_id,
    (1 - (0.05 + random() * 0.10))::numeric AS multiplier
  FROM income_bad_mutated.income_observation_mutated
  WHERE (
      series_code = 'RPI'
      AND observation_year BETWEEN 2011 AND 2018
      AND observation_month IN (1, 4, 7, 10)
    )
    OR (
      series_code = 'DSPI'
      AND observation_month IN (3, 6, 9, 12)
      AND observation_year BETWEEN 2006 AND 2022
    )
    OR (
      series_code = 'FODSP'
      AND observation_year IN (2002, 2007, 2012, 2017, 2022)
    )
)
UPDATE income_bad_mutated.income_observation_mutated target
SET
  observation_value = target.original_value * selected_mutations.multiplier,
  mutation_type = 'row_specific_percentage_decrease',
  mutation_note = 'Row-specific decrease of '
    || ROUND(((1 - selected_mutations.multiplier) * 100)::numeric, 2)::text
    || ' percent.'
FROM selected_mutations
WHERE target.observation_id = selected_mutations.observation_id;

-- Specific break:
--   Push several arbitrary rows up or down by one or two orders of magnitude.
--   Multipliers are randomly assigned from 0.01, 0.1, 10, and 100.
-- Display impact:
--   These selected values become obvious spikes or collapses and strongly
--   distort regression and prediction models. mutation_type only targets rows
--   that have not already been changed by the percentage updates above.
WITH ranked_candidates AS (
  SELECT
    observation_id,
    series_code,
    observation_year,
    observation_month,
    ROW_NUMBER() OVER (
      PARTITION BY series_code
      ORDER BY observation_date
    ) AS row_number_in_series
  FROM income_bad_mutated.income_observation_mutated
  WHERE mutation_type = 'none'
), selected_mutations AS (
  SELECT
    observation_id,
    CASE FLOOR(random() * 4)::integer
      WHEN 0 THEN 0.01::numeric
      WHEN 1 THEN 0.10::numeric
      WHEN 2 THEN 10.00::numeric
      ELSE 100.00::numeric
    END AS multiplier
  FROM ranked_candidates
  WHERE (
      series_code = 'MEHOINUSA646N'
      AND observation_year IN (2001, 2008, 2016, 2021)
    )
    OR (
      series_code = 'DSPI'
      AND row_number_in_series % 37 = 0
    )
    OR (
      series_code = 'PI'
      AND row_number_in_series % 41 = 0
    )
    OR (
      series_code = 'RPI'
      AND row_number_in_series % 43 = 0
    )
    OR (
      series_code = 'FODSP'
      AND observation_year IN (2005, 2010, 2015, 2020)
    )
)
UPDATE income_bad_mutated.income_observation_mutated target
SET
  observation_value = target.original_value * selected_mutations.multiplier,
  mutation_type = CASE
    WHEN selected_mutations.multiplier IN (10.00, 100.00)
      THEN 'random_order_of_magnitude_increase'
    ELSE 'random_order_of_magnitude_decrease'
  END,
  mutation_note = CASE
    WHEN selected_mutations.multiplier = 100.00
      THEN 'Randomly increased by two orders of magnitude by multiplying by 100.'
    WHEN selected_mutations.multiplier = 10.00
      THEN 'Randomly increased by one order of magnitude by multiplying by 10.'
    WHEN selected_mutations.multiplier = 0.10
      THEN 'Randomly decreased by one order of magnitude by multiplying by 0.10.'
    ELSE 'Randomly decreased by two orders of magnitude by multiplying by 0.01.'
  END
FROM selected_mutations
WHERE target.observation_id = selected_mutations.observation_id;

CREATE OR REPLACE VIEW income_bad_mutated.v_observations_long AS
SELECT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  original_value,
  observation_value,
  observation_value - original_value AS value_difference,
  CASE
    WHEN original_value = 0 THEN NULL
    ELSE ((observation_value - original_value) / original_value) * 100
  END AS percent_difference,
  mutation_type,
  mutation_note,
  source_file
FROM income_bad_mutated.income_observation_mutated;

-- Plot view:
--   Still returns date and zhvi for the current R plotting script, but it uses
--   the mutated median-income values rather than the clean values.
CREATE OR REPLACE VIEW income_bad_mutated.v_plot_data AS
SELECT
  observation_date AS date,
  observation_value AS zhvi
FROM income_bad_mutated.v_observations_long
WHERE series_code = 'MEHOINUSA646N'
ORDER BY observation_date;

-- Summary view:
--   Shows how many rows were changed and the size of the average shift.
CREATE OR REPLACE VIEW income_bad_mutated.v_mutation_summary AS
SELECT
  series_code,
  mutation_type,
  COUNT(*) AS row_count,
  AVG(original_value) AS average_original_value,
  AVG(observation_value) AS average_mutated_value,
  AVG(observation_value - original_value) AS average_difference,
  MIN(observation_value - original_value) AS minimum_difference,
  MAX(observation_value - original_value) AS maximum_difference,
  MIN(
    CASE
      WHEN original_value = 0 THEN NULL
      ELSE ((observation_value - original_value) / original_value) * 100
    END
  ) AS minimum_percent_difference,
  MAX(
    CASE
      WHEN original_value = 0 THEN NULL
      ELSE ((observation_value - original_value) / original_value) * 100
    END
  ) AS maximum_percent_difference
FROM income_bad_mutated.v_observations_long
GROUP BY
  series_code,
  mutation_type
ORDER BY
  series_code,
  mutation_type;
