-- Intentionally malformed schema variation 5: mutated values.
-- Run this script while connected to final_project_housing_analysis.
--
-- Purpose:
--   This version starts with the clean loaded data, then changes selected
--   numeric values in the copied schema only. The original income schema is
--   not changed.
--
-- What the correct result should look like:
--   observation_value should match the source CSV value exactly after loading.
--
-- Where this version breaks:
--   income_bad_mutated.income_observation_mutated stores both original_value
--   and observation_value. observation_value is intentionally wrong for
--   selected rows.
--
-- Prerequisite:
--   Run 01_create_income_schema.sql, 02_create_staging_tables.sql, import the
--   CSVs, then run 03_normalize_staged_income_data.sql first.

DROP SCHEMA IF EXISTS income_bad_mutated CASCADE;
CREATE SCHEMA income_bad_mutated;

CREATE TABLE income_bad_mutated.income_observation_mutated (
  observation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_date DATE NOT NULL,
  observation_year SMALLINT NOT NULL,
  observation_month SMALLINT NOT NULL,
  observation_quarter SMALLINT NOT NULL,
  series_code VARCHAR(32) NOT NULL,
  series_name TEXT NOT NULL,
  frequency_code VARCHAR(16) NOT NULL,
  units TEXT NOT NULL,
  source_file TEXT NOT NULL,
  original_value NUMERIC NOT NULL,
  observation_value NUMERIC NOT NULL,
  mutation_type TEXT NOT NULL DEFAULT 'none',
  mutation_note TEXT
);

-- Copy the clean data first. original_value remains unchanged for comparison.
INSERT INTO income_bad_mutated.income_observation_mutated (
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  source_file,
  original_value,
  observation_value
)
SELECT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  source_file,
  observation_value AS original_value,
  observation_value
FROM income.v_income_observations_long;

-- Specific break:
--   Add a zero to later median household income values.
-- Display impact:
--   The plotted annual line jumps by one order of magnitude after 2015.
UPDATE income_bad_mutated.income_observation_mutated
SET
  observation_value = original_value * 10,
  mutation_type = 'order_of_magnitude_increase',
  mutation_note = 'Added a zero by multiplying the value by 10.'
WHERE series_code = 'MEHOINUSA646N'
  AND observation_year >= 2015;

-- Specific break:
--   Drop a zero from FODSP values during 2008-2010.
-- Display impact:
--   The series dips far below its surrounding values.
UPDATE income_bad_mutated.income_observation_mutated
SET
  observation_value = original_value / 10,
  mutation_type = 'order_of_magnitude_decrease',
  mutation_note = 'Dropped a zero by dividing the value by 10.'
WHERE series_code = 'FODSP'
  AND observation_year BETWEEN 2008 AND 2010;

-- Specific break:
--   Increase personal income by 18 percent after 2020.
-- Display impact:
--   PI appears to rise faster than the clean data supports.
UPDATE income_bad_mutated.income_observation_mutated
SET
  observation_value = original_value * 1.18,
  mutation_type = 'percentage_increase',
  mutation_note = 'Increased by 18 percent.'
WHERE series_code = 'PI'
  AND observation_year >= 2020;

-- Specific break:
--   Decrease real personal income by 14 percent from 2012-2016.
-- Display impact:
--   RPI appears artificially weaker during those years.
UPDATE income_bad_mutated.income_observation_mutated
SET
  observation_value = original_value * 0.86,
  mutation_type = 'percentage_decrease',
  mutation_note = 'Decreased by 14 percent.'
WHERE series_code = 'RPI'
  AND observation_year BETWEEN 2012 AND 2016;

-- Specific break:
--   Increase quarter-ending DSPI values by 7 percent.
-- Display impact:
--   DSPI gets regular artificial bumps in March, June, September, and December.
UPDATE income_bad_mutated.income_observation_mutated
SET
  observation_value = original_value * 1.07,
  mutation_type = 'recurring_percentage_increase',
  mutation_note = 'Quarter-ending month increased by 7 percent.'
WHERE series_code = 'DSPI'
  AND observation_month IN (3, 6, 9, 12);

CREATE OR REPLACE VIEW income_bad_mutated.v_observations_long AS
SELECT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  original_value,
  observation_value,
  observation_value - original_value AS value_difference,
  CASE
    WHEN original_value = 0 THEN NULL
    ELSE ((observation_value - original_value) / original_value) * 100
  END AS percent_difference,
  mutation_type,
  mutation_note,
  source_file
FROM income_bad_mutated.income_observation_mutated;

-- Plot view:
--   Still returns date and zhvi for the current R plotting script, but it uses
--   the mutated median-income values rather than the clean values.
CREATE OR REPLACE VIEW income_bad_mutated.v_plot_data AS
SELECT
  observation_date AS date,
  observation_value AS zhvi
FROM income_bad_mutated.v_observations_long
WHERE series_code = 'MEHOINUSA646N'
ORDER BY observation_date;

-- Summary view:
--   Shows how many rows were changed and the size of the average shift.
CREATE OR REPLACE VIEW income_bad_mutated.v_mutation_summary AS
SELECT
  series_code,
  mutation_type,
  COUNT(*) AS row_count,
  AVG(original_value) AS average_original_value,
  AVG(observation_value) AS average_mutated_value,
  AVG(observation_value - original_value) AS average_difference
FROM income_bad_mutated.v_observations_long
GROUP BY
  series_code,
  mutation_type
ORDER BY
  series_code,
  mutation_type;
