-- Intentionally malformed schema variation 5: mutated values.
-- Run this script while connected to final_project_housing_analysis.
--
-- Purpose:
--   This version starts with the clean loaded data, then changes selected
--   numeric values in the copied schema only. The original income schema is
--   not changed.
--
-- What the correct result should look like:
--   observation_value should match the source CSV value exactly after loading.
--
-- Where this version breaks:
--   income_bad_mutated.income_observation_mutated stores both original_value
--   and observation_value. observation_value is intentionally wrong for
--   selected rows.
--
-- Prerequisite:
--   Run 01_create_income_schema.sql, 02_create_staging_tables.sql, import the
--   CSVs, then run 03_normalize_staged_income_data.sql first.

DROP SCHEMA IF EXISTS income_bad_mutated CASCADE;
CREATE SCHEMA income_bad_mutated;

CREATE TABLE income_bad_mutated.income_observation_mutated (
  observation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_date DATE NOT NULL,
  observation_year SMALLINT NOT NULL,
  observation_month SMALLINT NOT NULL,
  observation_quarter SMALLINT NOT NULL,
  series_code VARCHAR(32) NOT NULL,
  series_name TEXT NOT NULL,
  frequency_code VARCHAR(16) NOT NULL,
  units TEXT NOT NULL,
  source_file TEXT NOT NULL,
  original_value NUMERIC NOT NULL,
  observation_value NUMERIC NOT NULL,
  mutation_type TEXT NOT NULL DEFAULT 'none',
  mutation_note TEXT
);

-- Copy the clean data first. original_value remains unchanged for comparison.
INSERT INTO income_bad_mutated.income_observation_mutated (
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  source_file,
  original_value,
  observation_value
)
SELECT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  source_file,
  observation_value AS original_value,
  observation_value
FROM income.v_income_observations_long;

-- Specific break:
--   Apply row-specific percentage increases between 5 and 15 percent.
--   random() is evaluated per selected row, so each changed row receives a
--   different multiplier each time this script is rerun.
-- Display impact:
--   Individual rows drift upward without creating a long carried-forward run.
WITH mutation_targets(series_code, observation_date) AS (
  VALUES
    ('PI', DATE '2003-05-01'),
    ('PI', DATE '2011-08-01'),
    ('PI', DATE '2018-11-01'),
    ('PI', DATE '2024-02-01'),
    ('RPI', DATE '2006-02-01'),
    ('RPI', DATE '2014-09-01'),
    ('DSPI', DATE '2002-10-01'),
    ('DSPI', DATE '2019-05-01'),
    ('FODSP', DATE '2007-07-01'),
    ('MEHOINUSA646N', DATE '2014-01-01')
), selected_mutations AS (
  SELECT
    data.observation_id,
    (1 + (0.05 + random() * 0.10))::numeric AS multiplier
  FROM income_bad_mutated.income_observation_mutated data
  JOIN mutation_targets targets
    ON targets.series_code = data.series_code
   AND targets.observation_date = data.observation_date
)
UPDATE income_bad_mutated.income_observation_mutated target
SET
  observation_value = target.original_value * selected_mutations.multiplier,
  mutation_type = 'row_specific_percentage_increase',
  mutation_note = 'Row-specific increase of '
    || ROUND(((selected_mutations.multiplier - 1) * 100)::numeric, 2)::text
    || ' percent.'
FROM selected_mutations
WHERE target.observation_id = selected_mutations.observation_id;

-- Specific break:
--   Apply row-specific percentage decreases between 5 and 15 percent.
--   Each selected row receives its own randomized drop.
-- Display impact:
--   Individual rows develop local dips that can distort trend and forecast
--   models without creating a repeated visual pattern.
WITH mutation_targets(series_code, observation_date) AS (
  VALUES
    ('PI', DATE '2001-09-01'),
    ('PI', DATE '2016-04-01'),
    ('RPI', DATE '2008-10-01'),
    ('RPI', DATE '2021-03-01'),
    ('DSPI', DATE '2006-06-01'),
    ('DSPI', DATE '2013-12-01'),
    ('DSPI', DATE '2022-08-01'),
    ('FODSP', DATE '2002-04-01'),
    ('FODSP', DATE '2017-10-01'),
    ('MEHOINUSA646N', DATE '2019-01-01')
), selected_mutations AS (
  SELECT
    data.observation_id,
    (1 - (0.05 + random() * 0.10))::numeric AS multiplier
  FROM income_bad_mutated.income_observation_mutated data
  JOIN mutation_targets targets
    ON targets.series_code = data.series_code
   AND targets.observation_date = data.observation_date
)
UPDATE income_bad_mutated.income_observation_mutated target
SET
  observation_value = target.original_value * selected_mutations.multiplier,
  mutation_type = 'row_specific_percentage_decrease',
  mutation_note = 'Row-specific decrease of '
    || ROUND(((1 - selected_mutations.multiplier) * 100)::numeric, 2)::text
    || ' percent.'
FROM selected_mutations
WHERE target.observation_id = selected_mutations.observation_id;

-- Specific break:
--   Push several arbitrary rows up or down by large but capped amounts.
--   These are intentionally bigger than the 5-15 percent mutations above, but
--   they stay within a range that will not flatten the rest of the plot.
-- Display impact:
--   These selected values become visible local spikes or dips without forcing
--   the full chart into horizontal-looking lines. mutation_type only targets
--   rows that have not already been changed by the percentage updates above.
WITH mutation_targets(series_code, observation_date, multiplier) AS (
  VALUES
    ('MEHOINUSA646N', DATE '2001-01-01', 1.85::numeric),
    ('MEHOINUSA646N', DATE '2008-01-01', 0.55::numeric),
    ('MEHOINUSA646N', DATE '2016-01-01', 1.60::numeric),
    ('MEHOINUSA646N', DATE '2021-01-01', 0.70::numeric),
    ('DSPI', DATE '2004-04-01', 1.75::numeric),
    ('DSPI', DATE '2011-11-01', 0.60::numeric),
    ('DSPI', DATE '2020-05-01', 1.90::numeric),
    ('PI', DATE '2005-03-01', 0.65::numeric),
    ('PI', DATE '2015-07-01', 2.00::numeric),
    ('PI', DATE '2023-10-01', 0.50::numeric),
    ('RPI', DATE '2009-12-01', 1.50::numeric),
    ('RPI', DATE '2018-06-01', 0.75::numeric),
    ('FODSP', DATE '2005-01-01', 1.80::numeric),
    ('FODSP', DATE '2010-04-01', 0.55::numeric),
    ('FODSP', DATE '2020-01-01', 1.60::numeric)
), selected_mutations AS (
  SELECT
    data.observation_id,
    targets.multiplier
  FROM income_bad_mutated.income_observation_mutated data
  JOIN mutation_targets targets
    ON targets.series_code = data.series_code
   AND targets.observation_date = data.observation_date
  WHERE mutation_type = 'none'
)
UPDATE income_bad_mutated.income_observation_mutated target
SET
  observation_value = target.original_value * selected_mutations.multiplier,
  mutation_type = CASE
    WHEN selected_mutations.multiplier > 1
      THEN 'capped_large_point_increase'
    ELSE 'capped_large_point_decrease'
  END,
  mutation_note = CASE
    WHEN selected_mutations.multiplier > 1
      THEN 'Arbitrarily increased by '
        || ROUND(((selected_mutations.multiplier - 1) * 100)::numeric, 2)::text
        || ' percent as a capped large point error.'
    ELSE 'Arbitrarily decreased by '
      || ROUND(((1 - selected_mutations.multiplier) * 100)::numeric, 2)::text
      || ' percent as a capped large point error.'
  END
FROM selected_mutations
WHERE target.observation_id = selected_mutations.observation_id;

CREATE OR REPLACE VIEW income_bad_mutated.v_observations_long AS
SELECT
  observation_date,
  observation_year,
  observation_month,
  observation_quarter,
  series_code,
  series_name,
  frequency_code,
  units,
  original_value,
  observation_value,
  observation_value - original_value AS value_difference,
  CASE
    WHEN original_value = 0 THEN NULL
    ELSE ((observation_value - original_value) / original_value) * 100
  END AS percent_difference,
  mutation_type,
  mutation_note,
  source_file
FROM income_bad_mutated.income_observation_mutated;

-- Plot view:
--   Still returns date and zhvi for the current R plotting script, but it uses
--   the mutated median-income values rather than the clean values.
CREATE OR REPLACE VIEW income_bad_mutated.v_plot_data AS
SELECT
  observation_date AS date,
  observation_value AS zhvi
FROM income_bad_mutated.v_observations_long
WHERE series_code = 'MEHOINUSA646N'
ORDER BY observation_date;

-- Summary view:
--   Shows how many rows were changed and the size of the average shift.
CREATE OR REPLACE VIEW income_bad_mutated.v_mutation_summary AS
SELECT
  series_code,
  mutation_type,
  COUNT(*) AS row_count,
  AVG(original_value) AS average_original_value,
  AVG(observation_value) AS average_mutated_value,
  AVG(observation_value - original_value) AS average_difference,
  MIN(observation_value - original_value) AS minimum_difference,
  MAX(observation_value - original_value) AS maximum_difference,
  MIN(
    CASE
      WHEN original_value = 0 THEN NULL
      ELSE ((observation_value - original_value) / original_value) * 100
    END
  ) AS minimum_percent_difference,
  MAX(
    CASE
      WHEN original_value = 0 THEN NULL
      ELSE ((observation_value - original_value) / original_value) * 100
    END
  ) AS maximum_percent_difference
FROM income_bad_mutated.v_observations_long
GROUP BY
  series_code,
  mutation_type
ORDER BY
  series_code,
  mutation_type;
